name: Docker Image Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - 
      name: Build the Docker image
      run: |
        docker build -t ghcr.io/samitkumarpatel/tool-jenkins:$(date '+%d%m%Y') -t ghcr.io/samitkumarpatel/tool-jenkins:latest .
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: push
      run: |
        docker push -a ghcr.io/samitkumarpatel/tool-jenkins
